export interface EspnTeam {
  leagueId: string;
  seasonId: number;
  id: number;
  abbreviation: string;
  name: string;
  ownerName: string;
  logoURL: string;
  roster?: RosterEntity[] | null;
  wins: number;
  losses: number;
  ties: number;
  divisionWins: number;
  divisionLosses: number;
  divisionTies: number;
  homeWins: number;
  homeLosses: number;
  homeTies: number;
  awayWins: number;
  awayLosses: number;
  awayTies: number;
  totalPointsScored: number;
  regularSeasonPointsFor: number;
  regularSeasonPointsAgainst: number;
  winningPercentage: number;
  playoffSeed: number;
  finalStandingsPosition: number;
}
export interface RosterEntity {
  seasonId: number;
  scoringPeriodId: number;
  id: number;
  firstName: string;
  fullName: string;
  lastName: string;
  proTeam: string;
  proTeamAbbreviation: string;
  defaultPosition: string;
  eligiblePositions?: string[] | null;
  averageDraftPosition: number;
  auctionValueAverage: number;
  percentChange: number;
  percentStarted: number;
  percentOwned: number;
  availabilityStatus: string;
  isDroppable: boolean;
  isInjured: boolean;
  injuryStatus?: string | null;
  outlooksByWeek?: OutlooksByWeek | null;
}
export interface OutlooksByWeek {
  1: string;
  2: string;
  3: string;
  4?: string | null;
  5?: string | null;
  6?: string | null;
  7?: string | null;
  8?: string | null;
  10?: string | null;
  11?: string | null;
  12?: string | null;
  13?: string | null;
  14?: string | null;
  15?: string | null;
  16?: string | null;
  9?: string | null;
}

export interface espnRoster {
  appliedStatTotal: number;
  entries?: EntriesEntity[] | null;
  tradeReservedEntries: number;
}
export interface EntriesEntity {
  acquisitionDate: number;
  acquisitionType: string;
  injuryStatus: string;
  lineupSlotId: number;
  pendingTransactionIds?: null;
  playerId: number;
  playerPoolEntry: PlayerPoolEntry;
  status: string;
}
export interface PlayerPoolEntry {
  appliedStatTotal: number;
  id: number;
  keeperValue: number;
  keeperValueFuture: number;
  lineupLocked: boolean;
  onTeamId: number;
  player: Player;
  rosterLocked: boolean;
  status: string;
  tradeLocked: boolean;
}
export interface Player {
  active: boolean;
  defaultPositionId: number;
  draftRanksByRankType: DraftRanksByRankType;
  droppable: boolean;
  eligibleSlots?: number[] | null;
  firstName: string;
  fullName: string;
  id: number;
  injured: boolean;
  injuryStatus?: string | null;
  lastName: string;
  lastNewsDate?: number | null;
  outlooks?: Outlooks | null;
  ownership: Ownership;
  proTeamId: number;
  seasonOutlook?: string | null;
  stats?: StatsEntity[] | null;
  universeId: number;
  lastVideoDate?: number | null;
}
export interface DraftRanksByRankType {
  STANDARD: STANDARDOrPPR;
  PPR: STANDARDOrPPR;
}
export interface STANDARDOrPPR {
  auctionValue: number;
  published: boolean;
  rank: number;
  rankSourceId: number;
  rankType: string;
  slotId: number;
}
export interface Outlooks {
  outlooksByWeek: OutlooksByWeek;
}
export interface Ownership {
  auctionValueAverage: number;
  averageDraftPosition: number;
  percentChange: number;
  percentOwned: number;
  percentStarted: number;
}

export interface StatsEntity {
  appliedStats: AppliedStats;
  appliedTotal: number;
  externalId: string;
  id: string;
  proTeamId: number;
  scoringPeriodId: number;
  seasonId: number;
  statSourceId: number;
  statSplitTypeId: number;
  stats: Stats;
  variance?: Variance | null;
  appliedAverage?: number | null;
}
export interface AppliedStats {
  42?: number | null;
  43?: number | null;
  44?: number | null;
  53?: number | null;
  63?: number | null;
  72?: number | null;
  24?: number | null;
  25?: number | null;
  26?: number | null;
  3?: number | null;
  4?: number | null;
  19?: number | null;
  20?: number | null;
  101?: number | null;
  89?: number | null;
  90?: number | null;
  91?: number | null;
  92?: number | null;
  95?: number | null;
  99?: number | null;
  123?: number | null;
  124?: number | null;
  128?: number | null;
  129?: number | null;
  130?: number | null;
  132?: number | null;
  133?: number | null;
  134?: number | null;
  135?: number | null;
  136?: number | null;
  93?: number | null;
  96?: number | null;
  97?: number | null;
  98?: number | null;
  102?: number | null;
  103?: number | null;
  104?: number | null;
  125?: number | null;
  77?: number | null;
  80?: number | null;
  85?: number | null;
  86?: number | null;
  198?: number | null;
  201?: number | null;
}
export interface Stats {
  42?: number | null;
  43?: number | null;
  44?: number | null;
  45?: number | null;
  46?: number | null;
  47?: number | null;
  48?: number | null;
  49?: number | null;
  50?: number | null;
  51?: number | null;
  53?: number | null;
  54?: number | null;
  56?: number | null;
  57?: number | null;
  58?: number | null;
  60?: number | null;
  61?: number | null;
  62?: number | null;
  63?: number | null;
  67?: number | null;
  68?: number | null;
  71?: number | null;
  72?: number | null;
  73?: number | null;
  210?: number | null;
  213?: number | null;
  41?: number | null;
  52?: number | null;
  55?: number | null;
  59?: number | null;
  108?: number | null;
  109?: number | null;
  155?: number | null;
  156?: number | null;
  158?: number | null;
  183?: number | null;
  184?: number | null;
  186?: number | null;
  23?: number | null;
  24?: number | null;
  39?: number | null;
  40?: number | null;
  64?: number | null;
  107?: number | null;
  185?: number | null;
  25?: number | null;
  26?: number | null;
  27?: number | null;
  28?: number | null;
  35?: number | null;
  36?: number | null;
  37?: number | null;
  38?: number | null;
  66?: number | null;
  70?: number | null;
  212?: number | null;
  106?: number | null;
  29?: number | null;
  30?: number | null;
  31?: number | null;
  33?: number | null;
  34?: number | null;
  0?: number | null;
  1?: number | null;
  2?: number | null;
  3?: number | null;
  4?: number | null;
  5?: number | null;
  6?: number | null;
  7?: number | null;
  8?: number | null;
  9?: number | null;
  10?: number | null;
  11?: number | null;
  12?: number | null;
  15?: number | null;
  16?: number | null;
  17?: number | null;
  18?: number | null;
  19?: number | null;
  20?: number | null;
  21?: number | null;
  22?: number | null;
  65?: number | null;
  69?: number | null;
  211?: number | null;
  13?: number | null;
  14?: number | null;
  32?: number | null;
  175?: number | null;
  176?: number | null;
  177?: number | null;
  178?: number | null;
  179?: number | null;
  180?: number | null;
  101?: number | null;
  114?: number | null;
  116?: number | null;
  117?: number | null;
  181?: number | null;
  89?: number | null;
  90?: number | null;
  91?: number | null;
  92?: number | null;
  95?: number | null;
  99?: number | null;
  100?: number | null;
  110?: number | null;
  111?: number | null;
  112?: number | null;
  113?: number | null;
  115?: number | null;
  118?: number | null;
  120?: number | null;
  121?: number | null;
  122?: number | null;
  123?: number | null;
  124?: number | null;
  127?: number | null;
  128?: number | null;
  129?: number | null;
  130?: number | null;
  131?: number | null;
  132?: number | null;
  133?: number | null;
  134?: number | null;
  135?: number | null;
  136?: number | null;
  187?: number | null;
  188?: number | null;
  189?: number | null;
  190?: number | null;
  191?: number | null;
  192?: number | null;
  193?: number | null;
  194?: number | null;
  195?: number | null;
  93?: number | null;
  94?: number | null;
  96?: number | null;
  97?: number | null;
  98?: number | null;
  102?: number | null;
  103?: number | null;
  104?: number | null;
  105?: number | null;
  125?: number | null;
  126?: number | null;
  137?: number | null;
  160?: number | null;
  119?: number | null;
  182?: number | null;
  74?: number | null;
  75?: number | null;
  76?: number | null;
  77?: number | null;
  78?: number | null;
  79?: number | null;
  80?: number | null;
  81?: number | null;
  82?: number | null;
  83?: number | null;
  84?: number | null;
  85?: number | null;
  86?: number | null;
  87?: number | null;
  88?: number | null;
  198?: number | null;
  199?: number | null;
  200?: number | null;
  214?: number | null;
  215?: number | null;
  216?: number | null;
  221?: number | null;
  227?: number | null;
  233?: number | null;
  201?: number | null;
  202?: number | null;
  217?: number | null;
  218?: number | null;
  219?: number | null;
  220?: number | null;
  222?: number | null;
  229?: number | null;
  230?: number | null;
  231?: number | null;
  232?: number | null;
  234?: number | null;
}
export interface Variance {
  93?: number | null;
  94?: number | null;
  95?: number | null;
  96?: number | null;
  97?: number | null;
  98?: number | null;
  99?: number | null;
  101?: number | null;
  102?: number | null;
  103?: number | null;
  104?: number | null;
  106?: number | null;
  113?: number | null;
  114?: number | null;
  115?: number | null;
  120?: number | null;
  127?: number | null;
  0?: number | null;
  1?: number | null;
  3?: number | null;
  4?: number | null;
  15?: number | null;
  16?: number | null;
  19?: number | null;
  20?: number | null;
  23?: number | null;
  24?: number | null;
  25?: number | null;
  26?: number | null;
  35?: number | null;
  36?: number | null;
  44?: number | null;
  63?: number | null;
  64?: number | null;
  68?: number | null;
  72?: number | null;
  42?: number | null;
  43?: number | null;
  45?: number | null;
  46?: number | null;
  53?: number | null;
  58?: number | null;
  74?: number | null;
  75?: number | null;
  76?: number | null;
  77?: number | null;
  78?: number | null;
  79?: number | null;
  80?: number | null;
  81?: number | null;
  82?: number | null;
  83?: number | null;
  84?: number | null;
  85?: number | null;
  86?: number | null;
  87?: number | null;
  88?: number | null;
  198?: number | null;
  199?: number | null;
  200?: number | null;
}
